# Generated by Django 3.0.14 on 2021-08-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='status',
            new_name='condition',
        ),
    ]
